#!/usr/bin/env python3

import sys

from Xor.Xor import Xor

def xorTests():

    #-b test
    xor = Xor("576861742069732064656164206d6179206e6576657220646965")
    cypher = xor._encrypt("You know nothing, Jon Snow")
    assert cypher == "20070f2700071c6a4449060a490515164e4e12190b190011063c"
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow"

    # #Long key test
    xor = Xor("576861742069732064656164206d6179206e65766572206469651234")
    cypher = xor._encrypt("You know nothing, Jon Snow")
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow"

    # #Short key test
    xor = Xor("576861742069732064656164206d6179206e6576657220646965")
    cypher = xor._encrypt("You know nothing, Jon Snow is the best")
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow is the best"

def main():
    xorTests()

if __name__ == "__main__":
    main()
    print("Everything's good")
