#!/usr/bin/env python3

import sys

from Xor.Xor import Xor
from Aes.AES import Aes

def xorTests():

    #-b test
    xor = Xor("576861742069732064656164206d6179206e6576657220646965")
    cypher = xor._encrypt("You know nothing, Jon Snow")
    assert cypher == "20070f2700071c6a4449060a490515164e4e12190b190011063c"
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow"

    # Long key test
    xor = Xor("576861742069732064656164206d6179206e65766572206469651234")
    cypher = xor._encrypt("You know nothing, Jon Snow")
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow"

    # Short key test
    xor = Xor("576861742069732064656164206d6179206e6576657220646965")
    cypher = xor._encrypt("You know nothing, Jon Snow is the best")
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow is the best"

def aesTests():

    #-b test
    aes = Aes("57696e74657220697320636f6d696e67")
    cypher = aes._encrypt("All men must die")
    assert cypher == "744ce22c385958348f0df26eceb62eef"
    decypher = aes._decrypt("744ce22c385958348f0df26eceb62eef")
    assert decypher == "All men must die"

    # Short messag test
    aes = Aes("57696e74657220697320636f6d696e67")
    cypher = aes._encrypt("All men must d")
    assert cypher == "6449baa56dbe4ee34ea89a6d2dcb92b9"
    decypher = aes._decrypt("6449baa56dbe4ee34ea89a6d2dcb92b9")
    assert decypher == "All men must d"

    # Long messag test
    aes = Aes("57696e74657220697320636f6d696e67")
    cypher = aes._encrypt("All men must die ahah")
    assert cypher == "744ce22c385958348f0df26eceb62eefdd1ff81962eabbbdae56423d2d9df7dd"
    decypher = aes._decrypt("744ce22c385958348f0df26eceb62eefdd1ff81962eabbbdae56423d2d9df7dd")
    assert decypher == "All men must die ahah"

def main():
    xorTests()
    aesTests()

if __name__ == "__main__":
    main()
    print("Everything's good")
