#!/usr/bin/env python3

import sys

from Xor.Xor import Xor
from Aes.Aes import Aes

def xorTests():

    #-b test
    xor = Xor("576861742069732064656164206d6179206e6576657220646965")
    cypher = xor._encrypt("You know nothing, Jon Snow")
    assert cypher == "20070f2700071c6a4449060a490515164e4e12190b190011063c"
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow"

    # #Long key test
    xor = Xor("576861742069732064656164206d6179206e65766572206469651234")
    cypher = xor._encrypt("You know nothing, Jon Snow")
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow"

    # #Short key test
    xor = Xor("576861742069732064656164206d6179206e6576657220646965")
    cypher = xor._encrypt("You know nothing, Jon Snow is the best")
    decypher = xor._decrypt(cypher)
    assert decypher == "You know nothing, Jon Snow is the best"

def aesTests():

    #-b test
    cypher = Aes("All men must die", "57696e74657220697320636f6d696e67")
    assert cypher.cypherMessage() == "744ce22c385958348f0df26eceb62eef"
    decypher = Aes(cypher.cypherMessage(), "57696e74657220697320636f6d696e67")
    assert decypher.decypherMessage() == "All men must die"

def main():
    xorTests()
    aesTests()

if __name__ == "__main__":
    main()
    print("Everything's good")
